#!/bin/bash

TARGET_VERSION=$1
LOCATION=$2

if [ "x"$TARGET_VERSION = "x-h" -o "x"$TARGET_VERSION = "x--help" -o "x"$LOCATION = "x" ]; then
    echo "[usage] python-install VERSION LOCATION"
    echo "  ex: python-install 2.7.3 ~/local/python-2.7.3"
    exit 0
fi

cd $(dirname $0)
XBUILD_PATH=$(pwd)

if [ ! -d ./var/python-build ]; then
    (
        set -e
        mkdir -p var
        cd var
        git clone -q git://github.com/yyuu/pyenv.git pyenv-repo
        cd pyenv-repo/plugins/python-build
        PREFIX=$XBUILD_PATH/var/python-build ./install.sh >/dev/null 2>&1
    ) || (echo "failed to download python-build" && exit 1)
fi

echo "Start to build python $TARGET_VERSION ..."
./var/python-build/bin/python-build $TARGET_VERSION $LOCATION > /tmp/$USER-python-install.log 2>&1
RETVAL=$?
if [ $RETVAL != 0 ]; then
    echo "python-build failed. see log: /tmp/$USER-python-install.log"
    exit 1
fi

echo "python $TARGET_VERSION successfully installed on $LOCATION"
echo "To use this python, do 'export PATH=$LOCATION/bin:\$PATH'."
